### ISSUE TITLE
the backticks only work if the file is a fully formed Rmd with a header

### ISSUE THREAD

**Issue by markziemann** [nitinsharmagroup/Bioinformatics-assignment#2]
https://github.com/nitinsharmagroup/Bioinformatics-assignment/blob/862121758732d88d7a65d169bbc31058446e5627/Assignment.Rmd#L4

**Comment by nitinsharmagroup** [comment]
Dear Sir

The backticks have been removed.

Thanks for the feedback.

Nitin Sharma
